"use client";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { X } from "lucide-react";
import { useState } from "react";
const images=[
 ["hero-banner.png","Enterprise AI Business Intelligence Platform","Natural language analytics with governed query execution."],
 ["business-intelligence-workflow.png","Business intelligence workflow","Question to validated query, dashboard, and executive recommendation."],
 ["workspace.png","AI query workspace","Connection, schema, generated SQL, results, charts, and insight in one reviewable flow."],
 ["pipeline.png","Natural-language pipeline","Intent, schema context, prompt construction, generation, validation, repair, and export."],
 ["connection-manager.png","Multi-database connection manager","PostgreSQL, MySQL, and Oracle metadata remain explicit before query execution."],
 ["schema-explorer.png","Schema explorer","Tables, keys, relationships, and sample values help constrain generated SQL."],
 ["analytics-dashboard.png","Executive analytics dashboard","KPIs, filters, trends, and recommendations surface decisions rather than raw query output."],
 ["executive-report.png","Executive report","Findings, risks, and recommended actions are exportable for decision-makers."],
 ["security-dashboard.png","Security controls","Read-only policies, audit history, JWT sessions, rate limits, and blocked statements."],
 ["sql-repair.png","Self-healing SQL","Database feedback is converted into a constrained repair attempt before execution."],
 ["mobile-dashboard.png","Mobile executive dashboard","Saved reports, alerts, and essential KPIs remain usable away from the desktop."],
 ["system-architecture.png","Production architecture","React, FastAPI, policy boundaries, databases, charts, and export paths are independently deployable."],
] as const;
const stages=["Natural language","Intent detection","Schema understanding","Prompt builder","Groq LLM","SQL generation","Validation","Self-healing","Execution","Charts","AI summary","Export"];
const decisions=[["Why FastAPI?","Async request handling and typed contracts suit connection tests, query policies, and streaming-style progress.","Requires disciplined service boundaries as the domain grows."],["Why validation first?","Generated SQL is parsed and constrained before it can reach a database.","Adds a round trip, but converts a model suggestion into a governed action."],["Why multi-database?","Business data rarely lives in a single engine; dialect metadata keeps switching explicit.","Each engine adds a policy and prompt surface to test."],["Why self-healing SQL?","Database errors provide concrete feedback for a bounded repair loop.","Repairs remain revalidated; the system never retries destructive statements."]];
export default function AIDatabaseDeepDive(){const [active,setActive]=useState<number|null>(null);return <div className="space-y-24 pb-28"><section className="mx-auto max-w-[1000px] px-6"><div className="surface overflow-hidden rounded-3xl"><Image src="/images/ai-database-assistant/hero-banner.png" alt="AI Database Assistant enterprise business intelligence platform" width={1920} height={1080} priority className="h-auto w-full object-contain"/><div className="p-6 sm:p-8"><div className="eyebrow">Enterprise AI Business Intelligence Platform</div><h2 className="mt-2 text-3xl">Natural language analytics with governed execution.</h2><p className="mt-4 max-w-3xl text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>Business teams need answers from operational data without learning SQL dialects or waiting for a dashboard backlog. The system translates a question into a constrained, explainable query path and returns results that can be reviewed, visualized, and exported.</p></div></div></section>
<section id="workflow" className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">Solution workflow</div><h2 className="mt-2 text-3xl">From question to a decision-ready result.</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><button onClick={()=>setActive(1)} className="group surface overflow-hidden rounded-2xl text-left"><Image src="/images/ai-database-assistant/business-intelligence-workflow.png" alt={images[1][1]} width={1920} height={1080} className="h-auto w-full transition-transform duration-500 group-hover:scale-[1.02]"/><span className="block p-4 text-xs" style={{color:"var(--text-dim)"}}>{images[1][2]}</span></button><div className="surface rounded-2xl p-6"><div className="eyebrow">Business problem</div><p className="mt-3 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>Business users cannot safely write SQL, analysts lose time assembling repeat dashboards, schemas are difficult to interpret, and database dialects make a single query approach unreliable.</p><div className="eyebrow mt-7">Solution</div><p className="mt-3 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>Schema-aware generation, read-only validation, dialect-specific execution, charts, and executive summaries turn the request into an auditable workflow instead of a chatbot response.</p></div></div></section>
<section className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">Natural-language pipeline</div><div className="mt-6 flex flex-wrap items-center gap-2">{stages.map((stage,index)=><div key={stage} className="flex items-center gap-2"><motion.span whileHover={{y:-3}} className="rounded-lg border px-3 py-2 text-xs" style={{borderColor:"var(--border)",background:"var(--glass)"}}>{stage}</motion.span>{index<stages.length-1&&<span style={{color:"var(--primary)"}}>→</span>}</div>)}</div><div className="mt-7 grid gap-4 md:grid-cols-2">{[["Multi-database support","PostgreSQL, MySQL, and Oracle connections are tested before use. Metadata and dialect rules constrain generated SQL rather than relying on a generic prompt."],["Security boundary","JWT sessions, refresh rotation, read-only SQL policy, blocked DELETE/DROP/ALTER statements, audit events, and separate rate limits keep analytics actions accountable."],["Executive analytics","Results become filters, KPIs, trends, narrative summaries, and exportable reports instead of one-off query output."],["Self-healing SQL","Errors enter a constrained repair path: database feedback → adjusted SQL → validation → execution. Repair improves usability without bypassing policy."]].map(([title,body])=><article key={title} className="surface rounded-2xl p-6"><h3 className="text-lg">{title}</h3><p className="mt-3 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>{body}</p></article>)}</div></section>
<section className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">Product surfaces</div><div className="mt-6 grid gap-4 md:grid-cols-2">{images.slice(2).map((image,index)=><button key={image[0]} onClick={()=>setActive(index+2)} className="group surface overflow-hidden rounded-2xl text-left"><div className="relative aspect-video"><Image src={`/images/ai-database-assistant/${image[0]}`} alt={image[1]} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition-transform duration-500 group-hover:scale-105"/></div><div className="p-4"><h3 className="text-sm font-semibold">{image[1]}</h3><p className="mt-1 text-xs" style={{color:"var(--text-dimmer)"}}>{image[2]}</p></div></button>)}</div></section>
<section className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">Engineering decisions</div><div className="mt-6 grid gap-4 md:grid-cols-2">{decisions.map(([title,solution,tradeoff])=><article key={title} className="surface rounded-2xl p-6"><h3 className="text-lg">{title}</h3><p className="mt-3 text-sm" style={{color:"var(--text-dim)"}}>{solution}</p><p className="mt-4 rounded-lg border p-3 text-xs" style={{borderColor:"var(--border)",color:"var(--text-dimmer)"}}><b style={{color:"var(--text)"}}>Tradeoff:</b> {tradeoff}</p></article>)}</div><div className="surface mt-5 rounded-2xl p-6"><div className="eyebrow">Performance and outcome</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Query validation","< 120ms"],["Connection health","< 1s"],["Repair success","guarded retry"],["Dashboard build","< 2s"],["Policy","read-only"],["Export","audited"]].map(([k,v])=><div key={k} className="rounded-xl border p-4" style={{borderColor:"var(--border)"}}><div className="mono text-xs" style={{color:"var(--text-dimmer)"}}>{k}</div><div className="mt-2 font-semibold" style={{color:"var(--primary)"}}>{v}</div></div>)}</div><p className="mt-5 text-sm" style={{color:"var(--text-dim)"}}>The measurable outcome is a governed path from a business question to an executive-ready result: fewer analyst handoffs, explicit database policies, multi-engine support, and explanations tied to the data returned.</p></div></section>
<section className="mx-auto max-w-[1000px] px-6"><div className="surface rounded-2xl p-6"><div className="eyebrow">Roadmap</div><p className="mt-3 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>Real-time dashboards, vector memory for recurring analysis, conversational BI, agent-assisted analytics, predictive modeling, voice queries, and scheduled reporting are logical extensions once the governed execution path is stable.</p></div></section>
<AnimatePresence>{active!==null&&<motion.div role="dialog" aria-modal="true" aria-label={images[active][1]} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)} className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/85 p-4"><motion.div onClick={event=>event.stopPropagation()} initial={{scale:.96}} animate={{scale:1}} exit={{scale:.96}} className="relative max-h-full max-w-6xl"><button onClick={()=>setActive(null)} aria-label="Close image" className="absolute -top-10 right-0 p-2 text-white"><X/></button><Image src={`/images/ai-database-assistant/${images[active][0]}`} alt={images[active][1]} width={1920} height={1080} priority className="max-h-[85vh] w-auto rounded-xl object-contain"/><p className="mt-3 text-center text-sm text-white/75">{images[active][2]}</p></motion.div></motion.div>}</AnimatePresence></div>}
