"use client";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { X } from "lucide-react";
import { useState } from "react";
const labels = ["Workspace overview", "System intelligence", "Delivery analytics"];
const repoMindImages=[
 {src:"/images/repomind/saas-dashboard.png",alt:"RepoMind AI dashboard showing repository metrics, retrieved context, and an authentication explanation",caption:"Repository intelligence workspace"},
 {src:"/images/repomind/architecture-pipeline.png",alt:"RepoMind AI architecture dashboard visualizing parsing, embeddings, Qdrant, MMR, reranking, compression, and streaming",caption:"Multi-stage retrieval architecture"},
 {src:"/images/repomind/repository-explorer.png",alt:"RepoMind AI repository explorer showing folders, embeddings, dependencies, and code complexity",caption:"Repository explorer and code understanding"},
];
export default function ProjectScreenshots({ name, accent }: { name:string; accent:string }) { const [active,setActive]=useState<number|null>(null);const repoMind=name==="RepoMind AI";return <section className="pb-16"><div className="mx-auto max-w-[1000px] px-6"><div className="eyebrow mb-5">{name} · Product surfaces</div>{repoMind?<div className="grid gap-4 md:grid-cols-3">{repoMindImages.map((image,index)=><button type="button" key={image.src} onClick={()=>setActive(index)} className="group surface overflow-hidden rounded-2xl text-left" aria-label={`Open ${image.caption} image`}><div className="relative aspect-square overflow-hidden"><Image src={image.src} alt={image.alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-500 group-hover:scale-105"/></div><div className="border-t px-4 py-3 text-xs" style={{borderColor:"var(--border)",color:"var(--text-dim)"}}>{String(index+1).padStart(2,"0")} · {image.caption}</div></button>)}</div>:<div className="grid gap-4 md:grid-cols-3">{labels.map((label,i)=><motion.div key={label} whileHover={{y:-5}} className="surface overflow-hidden rounded-2xl"><div className="flex h-40 flex-col p-4" style={{background:`linear-gradient(140deg, ${accent}22, transparent)`}}><div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-white/30"/><span className="h-2 w-2 rounded-full bg-white/20"/><span className="h-2 w-2 rounded-full bg-white/10"/></div><div className="mt-5 grid flex-1 grid-cols-[.35fr_1fr] gap-3"><div className="rounded-md bg-white/10"/><div className="space-y-2"><div className="h-3 w-3/4 rounded bg-white/30"/><div className="h-12 rounded bg-white/10"/><div className="h-3 w-1/2 rounded bg-white/20"/></div></div></div><div className="border-t px-4 py-3 text-xs" style={{borderColor:"var(--border)",color:"var(--text-dim)"}}>{String(i+1).padStart(2,"0")} · {label}</div></motion.div>)}</div>}<AnimatePresence>{active!==null&&<motion.div role="dialog" aria-modal="true" aria-label={repoMindImages[active].caption} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)} className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/85 p-4"><motion.div initial={{scale:.96}} animate={{scale:1}} exit={{scale:.96}} onClick={e=>e.stopPropagation()} className="relative max-h-full max-w-5xl"><button onClick={()=>setActive(null)} aria-label="Close image" className="absolute -top-10 right-0 rounded-full p-2 text-white"><X/></button><Image src={repoMindImages[active].src} alt={repoMindImages[active].alt} width={1024} height={1024} className="max-h-[85vh] w-auto rounded-xl object-contain" priority/><p className="mt-3 text-center text-sm text-white/75">{repoMindImages[active].caption}</p></motion.div></motion.div>}</AnimatePresence></div></section> }
