"use client";
import { motion } from "framer-motion";
import { useState } from "react";
import { Activity, Code2, LockKeyhole, Radio } from "lucide-react";

const stages=[
 ["01","Repository scanning","Walk the repository once, respect .gitignore, and record only source material worth indexing.","Avoids indexing vendored code and build output."],
 ["02","Structure-aware chunks","AST boundaries preserve functions, classes, imports, and surrounding intent.","More work at ingestion for higher retrieval quality."],
 ["03","Embedding generation","Sentence Transformers encode code and documentation into a shared semantic space.","Fast local recall, with model quality as a tunable cost."],
 ["04","Vector search","Qdrant returns a broad candidate set for the user’s question.","Recall is intentionally optimized before precision."],
 ["05","MMR diversification","Maximal marginal relevance removes near-duplicate candidates.","Slightly more compute prevents repetitive context."],
 ["06","Lexical reranking","Keyword and path signals elevate exact symbols and files.","Semantic similarity alone misses identifiers."],
 ["07","Context compression","Only the spans that answer the question enter the prompt.","Reduces token cost and distractor context."],
 ["08","Prompt construction","Instructions, citations, and retrieved context are assembled deterministically.","Keeps answers grounded in the repository."],
 ["09","LLM generation","The model explains code with evidence rather than guessing.","Provider choice remains isolated behind an adapter."],
 ["10","SSE streaming","Tokens reach the browser as they are generated, with keepalives and clean shutdown.","Perceived latency stays low without hiding failures."],
] as const;
const tabs={Backend:"FastAPI owns request validation, repository jobs, and streaming endpoints. Domain services keep ingestion, retrieval, and generation independently testable.",Frontend:"React keeps the explorer responsive while SSE progressively renders cited answers and source panels.",Retrieval:"Qdrant performs semantic recall; MMR and lexical reranking improve the context set before generation.",Authentication:"bcrypt password verification, short-lived JWT access tokens, refresh rotation, hashed refresh records, and role-aware API guards.",Containers:"Docker Compose wires the API, worker, Qdrant, and reverse proxy into repeatable local and deployment environments.",Infrastructure:"Nginx terminates edge traffic, telemetry captures system signals, and health checks make failures visible.",Testing:"Unit tests cover chunking and policies; integration tests cover retrieval quality, streamed responses, and protected routes."};
const snippets={"AST parser":"tree = parser.parse(source)\nfor node in tree.root_node.children:\n  chunks.extend(chunk_by_symbol(node))","MMR retrieval":"candidates = qdrant.search(vector, limit=40)\nselected = mmr(query, candidates, lambda_mult=0.65)","Prompt builder":"context = compress(reranked, token_budget=6000)\nprompt = build_prompt(question, context, citations=True)","Streaming":"async for token in provider.stream(prompt):\n  yield f'data: {token}\\n\\n'","Security":"verify_password(password, user.password_hash)\nrequire_role(token, repository_id)"};
export default function RepoMindDeepDive(){const [tab,setTab]=useState<keyof typeof tabs>("Backend");const [code,setCode]=useState<keyof typeof snippets>("AST parser");return <div className="space-y-24 pb-28">
 <section className="mx-auto max-w-[1000px] px-6"><div className="surface rounded-3xl p-6 sm:p-9"><div className="eyebrow">Operational profile</div><h2 className="mt-3 text-3xl">The system behind the answer.</h2><p className="mt-4 max-w-3xl leading-relaxed" style={{color:"var(--text-dim)"}}>RepoMind is designed around a simple constraint: code answers are useful only when retrieval is precise, context is bounded, and the request path remains observable. The application treats generation as the last stage of a retrieval system—not the whole product.</p><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-3">{[["1k+","files indexed"],["10k+","code chunks"],["< 450ms","retrieval target"],["SSE","token delivery"],["JWT","protected access"],["Qdrant","vector store"]].map(([v,l])=><div key={l} className="rounded-xl border p-4" style={{borderColor:"var(--border)",background:"var(--glass)"}}><div className="text-xl font-semibold" style={{color:"var(--secondary)"}}>{v}</div><div className="mono mt-1 text-[10px]" style={{color:"var(--text-dimmer)"}}>{l}</div></div>)}</div></div></section>
 <section id="pipeline" className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">How retrieval works</div><h2 className="mt-2 text-3xl">Ten deliberate stages, each with a job.</h2><div className="mt-8 grid gap-3">{stages.map(([n,title,desc,trade])=><motion.div whileHover={{x:4}} key={n} className="surface grid gap-3 rounded-2xl p-5 md:grid-cols-[60px_1fr_1fr]"><span className="mono text-xs" style={{color:"var(--secondary)"}}>{n}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm" style={{color:"var(--text-dim)"}}>{desc}</p></div><p className="rounded-lg border p-3 text-xs leading-relaxed" style={{borderColor:"var(--border)",color:"var(--text-dimmer)"}}><b style={{color:"var(--text)"}}>Tradeoff:</b> {trade}</p></motion.div>)}</div></section>
 <section className="mx-auto grid max-w-[1000px] gap-5 px-6 md:grid-cols-2"><div className="surface rounded-2xl p-6"><div className="flex gap-2"><LockKeyhole style={{color:"var(--primary)"}}/><div><div className="eyebrow">Security boundary</div><h2 className="mt-2 text-2xl">Access is part of the architecture.</h2></div></div><div className="mt-6 space-y-2">{["Login → bcrypt verification","JWT access token → protected API","Refresh token → SHA256 persisted hash","Role validation → repository boundary","IP / user sliding window → fair rate limiting"].map(x=><div key={x} className="rounded-lg border p-3 text-sm" style={{borderColor:"var(--border)",color:"var(--text-dim)"}}>{x}</div>)}</div><p className="mt-4 text-xs" style={{color:"var(--text-dimmer)"}}>Separate IP and user windows avoid penalizing authenticated users sharing a NAT while still constraining anonymous traffic.</p></div><div className="surface rounded-2xl p-6"><div className="flex gap-2"><Radio style={{color:"var(--accent)"}}/><div><div className="eyebrow">Streaming engine</div><h2 className="mt-2 text-2xl">Answer delivery without the blank wait.</h2></div></div><div className="mt-6 flex flex-wrap items-center gap-2">{["Question","Retriever","LLM","SSE tokens","Browser render"].map((x,i)=><div key={x} className="flex items-center gap-2"><motion.div animate={{opacity:[.55,1,.55]}} transition={{delay:i*.2,duration:1.4,repeat:Infinity}} className="rounded-lg border px-3 py-2 text-xs" style={{borderColor:"var(--border)",background:"var(--glass)"}}>{x}</motion.div>{i<4&&<span style={{color:"var(--accent)"}}>→</span>}</div>)}</div><p className="mt-6 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>SSE emits a token stream with keepalives. Cancellation closes the upstream generation task, so disconnected clients do not keep expensive work alive.</p></div></section>
 <section className="mx-auto max-w-[1000px] px-6"><div className="surface rounded-3xl p-6 sm:p-8"><div className="flex items-center gap-2"><Activity style={{color:"var(--primary)"}}/><div><div className="eyebrow">Telemetry</div><h2 className="mt-1 text-2xl">Signals for the request path.</h2></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Retrieval","318 ms"],["Generation","1.8 s"],["Prompt tokens","2.4k"],["Compression","61%"],["Feedback","4.7 / 5"],["Error rate","< 1%"]].map(([k,v],i)=><div key={k} className="rounded-xl border p-4" style={{borderColor:"var(--border)"}}><div className="mono text-xs" style={{color:"var(--text-dimmer)"}}>{k}</div><div className="mt-2 text-xl font-semibold">{v}</div><motion.div initial={{width:0}} whileInView={{width:`${40+i*8}%`}} viewport={{once:true}} className="mt-4 h-1 rounded bg-[var(--primary)]"/></div>)}</div></div></section>
 <section className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">Implementation decisions</div><div className="mt-5 flex flex-wrap gap-2">{Object.keys(tabs).map(k=><button key={k} onClick={()=>setTab(k as keyof typeof tabs)} className="rounded-full border px-3 py-2 text-xs" style={{borderColor:tab===k?"var(--primary)":"var(--border)",background:tab===k?"var(--primary)":"transparent",color:tab===k?"#111":"var(--text-dim)"}}>{k}</button>)}</div><motion.div key={tab} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} className="surface mt-4 rounded-2xl p-6 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>{tabs[tab]}</motion.div><div className="mt-8 grid gap-4 md:grid-cols-[.7fr_1.3fr]"><div className="space-y-2">{Object.keys(snippets).map(k=><button key={k} onClick={()=>setCode(k as keyof typeof snippets)} className="block w-full rounded-lg border p-3 text-left text-sm" style={{borderColor:code===k?"var(--secondary)":"var(--border)",color:"var(--text-dim)"}}><Code2 className="mr-2 inline" size={14}/>{k}</button>)}</div><pre className="surface overflow-x-auto rounded-2xl p-6 text-xs leading-relaxed" style={{color:"var(--accent)"}}><code>{snippets[code]}</code></pre></div></section>
 <section className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">Results & roadmap</div><div className="mt-5 grid gap-4 md:grid-cols-2">{["Higher retrieval precision through reranking and diversified context","Lower redundant context before prompt construction","Visible latency, quality, and error signals across the request path","Repeatable Docker deployment with protected, tested API boundaries"].map((x,i)=><div key={x} className="surface rounded-2xl p-5"><span className="mono text-xs" style={{color:"var(--primary)"}}>0{i+1}</span><p className="mt-3 text-sm" style={{color:"var(--text-dim)"}}>{x}</p></div>)}</div><div className="mt-5 surface rounded-2xl p-6"><h3 className="text-xl">Next: make repository intelligence cumulative.</h3><p className="mt-3 text-sm" style={{color:"var(--text-dim)"}}>Multi-repository search, incremental indexing, code graphs, repository diffs, GitHub App integration, IDE workflows, and narrowly-scoped agentic tasks are the logical next steps.</p></div></section>
 </div>}
