"use client";
import { motion } from "framer-motion";
import { useState } from "react";
import { Activity, BrainCircuit, LockKeyhole, Network, Scale, ShieldCheck } from "lucide-react";
const pipeline=[
 ["Invoices","Signed uploads are isolated by tenant before processing.","PDF / image","Secure object storage","Unreadable scans → review queue"],
 ["OCR","Tesseract extracts raw text and layout signals.","Document image","Text blocks","Noise → confidence threshold"],
 ["Parser","Fields are normalized against expected invoice structure.","Raw text","Vendor, GSTIN, tax fields","Missing fields → manual resolution"],
 ["DuckDB analytics","Local analytical queries produce auditable aggregates.","Normalized rows","Transaction patterns","Large batch → incremental loads"],
 ["Knowledge graph","Relationships connect businesses, invoices, accounts, and addresses.","Entities and edges","Risk neighborhoods","Dense graph → bounded traversal"],
 ["Rule engine","Deterministic rules create explainable compliance signals.","Invoice facts","Violations","Conflicting rules → precedence"],
 ["Gemma reasoning","Local reasoning explains evidence without replacing policy.","Rules + graph context","Structured JSON","Prompt limit → compressed evidence"],
 ["Risk scoring","Weighted signals become an investigation priority.","Signals + confidence","Compliance score","False positive → reviewer feedback"],
 ["Investigation report","Evidence, rationale, and audit record are assembled.","Scored case","Report","Partial evidence → explicit caveat"],
] as const;
const rules=["Duplicate invoices","GST mismatch","Circular trading","Vendor blacklist","Suspicious tax patterns","Missing invoices","Amount anomalies","Confidence calculation"];
const challenges=[ ["OCR noise","Use field-level confidence, normalization, and an exception queue rather than trusting raw text.","More reviewer touchpoints, fewer silent data errors."],["Graph complexity","Bound traversal depth and precompute high-value relationship features.","A narrower graph is faster and easier to explain."],["Prompt limits","Compress rule evidence and graph context before Gemma reasoning.","Some detail is omitted, but supporting evidence remains traceable."],["False positives","Separate deterministic findings from model explanations and retain reviewer feedback.","Detection remains conservative in ambiguous cases."] ];
export default function ChakraDeepDive(){const [selected,setSelected]=useState(0);return <div className="space-y-24 pb-28"><section className="mx-auto max-w-[1000px] px-6"><div className="surface rounded-3xl p-7 sm:p-9"><div className="eyebrow">Executive overview</div><h2 className="mt-3 text-3xl">Compliance work is an evidence problem.</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{[["Business problem","Fraud and compliance investigations require manual review across thousands of invoices, vendors, and related entities."],["Approach","CHAKRA turns documents into normalized facts, relationship signals, deterministic violations, and human-readable investigation evidence."],["Business impact","Investigations start earlier, reviewers handle less repetitive work, and every risk signal retains a traceable explanation."]].map(([t,b])=><div key={t} className="rounded-2xl border p-5" style={{borderColor:"var(--border)",background:"var(--glass)"}}><h3 className="font-semibold">{t}</h3><p className="mt-3 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>{b}</p></div>)}</div></div></section>
<section className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">End-to-end platform pipeline</div><h2 className="mt-2 text-3xl">Every transformation has a boundary.</h2><div className="mt-8 grid gap-3">{pipeline.map(([name,purpose,input,output,failure],i)=><button key={name} onClick={()=>setSelected(i)} className="surface grid w-full gap-3 rounded-2xl p-5 text-left transition-transform hover:translate-x-1 md:grid-cols-[48px_1fr_1fr]" style={{borderColor:selected===i?"var(--accent)":"var(--border)"}}><span className="mono text-xs" style={{color:"var(--accent)"}}>{String(i+1).padStart(2,"0")}</span><div><h3 className="font-semibold">{name}</h3><p className="mt-2 text-sm" style={{color:"var(--text-dim)"}}>{purpose}</p></div><div className="rounded-lg border p-3 text-xs leading-relaxed" style={{borderColor:"var(--border)",color:"var(--text-dimmer)"}}><b style={{color:"var(--text)"}}>Input:</b> {input}<br/><b style={{color:"var(--text)"}}>Output:</b> {output}<br/><b style={{color:"var(--text)"}}>Failure:</b> {failure}</div></button>)}</div></section>
<section className="mx-auto grid max-w-[1000px] gap-5 px-6 md:grid-cols-2"><div className="surface rounded-2xl p-6"><div className="flex gap-3"><BrainCircuit style={{color:"var(--accent)"}}/><div><div className="eyebrow">How Gemma reasons</div><h2 className="mt-2 text-2xl">LLM reasoning follows evidence.</h2></div></div><div className="mt-6 space-y-2">{["Invoice → extracted fields","Compliance rules + graph context","Risk indicators → prompt builder","Gemma → structured JSON","Human explanation → review"].map(x=><div key={x} className="rounded-lg border p-3 text-sm" style={{borderColor:"var(--border)",color:"var(--text-dim)"}}>{x}</div>)}</div><p className="mt-5 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>Deterministic rules establish what happened. Gemma explains the evidence and groups it into an investigator-readable narrative; it does not silently override policy.</p></div><div className="surface rounded-2xl p-6"><div className="flex gap-3"><Network style={{color:"var(--primary)"}}/><div><div className="eyebrow">Knowledge graph</div><h2 className="mt-2 text-2xl">Relationships reveal the pattern.</h2></div></div><p className="mt-5 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>Businesses, invoices, GSTINs, transporters, bank accounts, CA firms, directors, and shared addresses become graph entities. Bounded traversals surface circular trading, repeated counterparties, and relationship concentration without treating correlation as proof.</p><div className="mt-5 flex flex-wrap gap-2">{["Businesses","Invoices","GSTIN","Bank accounts","Directors","Addresses"].map(x=><span key={x} className="rounded-full border px-3 py-2 text-xs" style={{borderColor:"var(--border)",color:"var(--text-dim)"}}>{x}</span>)}</div></div></section>
<section className="mx-auto max-w-[1000px] px-6"><div className="surface rounded-3xl p-7"><div className="flex items-center gap-3"><Scale style={{color:"var(--primary)"}}/><div><div className="eyebrow">Compliance and risk engine</div><h2 className="mt-1 text-2xl">Score evidence; do not hide the weighting.</h2></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{rules.map((rule,i)=><div key={rule} className="rounded-xl border p-4 text-sm" style={{borderColor:"var(--border)"}}><span className="mono text-xs" style={{color:"var(--accent)"}}>{String(i+1).padStart(2,"0")}</span><p className="mt-2">{rule}</p></div>)}</div><div className="mt-7 rounded-xl border p-5 text-center text-lg" style={{borderColor:"var(--border)",background:"var(--glass)"}}>Invoice risk + Vendor risk + Relationship risk + Rule violations + AI confidence <span style={{color:"var(--accent)"}}>→ Final compliance score</span></div><p className="mt-4 text-sm" style={{color:"var(--text-dim)"}}>Weights prioritize verified rule violations and repeat relationship evidence. AI confidence affects explanation confidence, not the underlying policy finding.</p></div></section>
<section className="mx-auto grid max-w-[1000px] gap-5 px-6 md:grid-cols-2"><div className="surface rounded-2xl p-6"><div className="flex gap-3"><LockKeyhole style={{color:"var(--primary)"}}/><div><div className="eyebrow">Security architecture</div><h2 className="mt-1 text-2xl">Sensitive documents stay compartmentalized.</h2></div></div><ul className="mt-6 space-y-3 text-sm" style={{color:"var(--text-dim)"}}>{["Role-based access and document isolation","Encrypted storage and secure upload validation","Audit and compliance logging for every investigation action","Scoped reports with no cross-tenant evidence leakage"].map(x=><li key={x}>• {x}</li>)}</ul></div><div className="surface rounded-2xl p-6"><div className="flex gap-3"><ShieldCheck style={{color:"var(--accent)"}}/><div><div className="eyebrow">Deployment</div><h2 className="mt-1 text-2xl">Local-first, containerized boundaries.</h2></div></div><div className="mt-6 flex flex-wrap items-center gap-2">{["Browser","Nginx","FastAPI","Gemma","DuckDB","Knowledge graph","Storage","Reports"].map((x,i)=><div key={x} className="flex items-center gap-2"><span className="rounded-lg border px-3 py-2 text-xs" style={{borderColor:"var(--border)"}}>{x}</span>{i<7&&<span style={{color:"var(--accent)"}}>→</span>}</div>)}</div><p className="mt-5 text-sm" style={{color:"var(--text-dim)"}}>Docker containers keep inference, analytics, graph processing, and reports independently deployable while preserving an offline-friendly data path.</p></div></section>
<section className="mx-auto max-w-[1000px] px-6"><div className="surface rounded-3xl p-7"><div className="flex gap-3"><Activity style={{color:"var(--primary)"}}/><div><div className="eyebrow">Performance envelope</div><h2 className="mt-1 text-2xl">Operational signals, not vanity metrics.</h2></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["OCR","0.8–2.4s"],["Rule evaluation","< 90ms"],["Graph search","< 180ms"],["AI analysis","2–6s"],["Report generation","< 3s"],["Memory target","< 2 GB"]].map(([k,v],i)=><div key={k} className="rounded-xl border p-4" style={{borderColor:"var(--border)"}}><div className="mono text-xs" style={{color:"var(--text-dimmer)"}}>{k}</div><div className="mt-2 text-xl font-semibold">{v}</div><motion.div initial={{width:0}} whileInView={{width:`${45+i*7}%`}} viewport={{once:true}} className="mt-4 h-1 rounded bg-[var(--accent)]"/></div>)}</div></div></section>
<section className="mx-auto max-w-[1000px] px-6"><div className="eyebrow">Engineering challenges</div><div className="mt-6 grid gap-4">{challenges.map(([challenge,solution,tradeoff],i)=><article key={challenge} className="surface grid gap-4 rounded-2xl p-6 md:grid-cols-[56px_1fr_1fr]"><span className="mono text-xs" style={{color:"var(--accent)"}}>{String(i+1).padStart(2,"0")}</span><div><h3 className="font-semibold">{challenge}</h3><p className="mt-2 text-sm" style={{color:"var(--text-dim)"}}>{solution}</p></div><p className="rounded-lg border p-3 text-sm" style={{borderColor:"var(--border)",color:"var(--text-dimmer)"}}><b style={{color:"var(--text)"}}>Tradeoff:</b> {tradeoff}</p></article>)}</div><div className="surface mt-5 rounded-2xl p-6"><div className="eyebrow">Roadmap</div><p className="mt-3 text-sm leading-relaxed" style={{color:"var(--text-dim)"}}>Real-time monitoring, government API integration, multilingual OCR, graph neural network features, agent-assisted investigations, continuous compliance, and legal-notice drafting can extend the platform without weakening its evidence-first core.</p></div></section>
</div>}
